### ISSUE TITLE
CSS import is affecting global scope

### ISSUE THREAD

**Issue by devth** [transitive-bullshit/create-react-library#140]
I'm importing Bulma in my component:

```javascript
import bulma from './bulma.css';
```

But when I include that component in another app it's injecting global bulma stuff into the entire site. I expected it to be scoped by default. 

Component is [here](https://github.com/devth/github-org-cards/blob/master/src/index.js). I'm using default config from CRL.

The injected css can be seen in the `<head>` section of https://yetibot.com/community where this component is being used. It includes a bunch of (expected) scoped rules like:

```css
.bulma_is-active__2ghUu.bulma_pagination-ellipsis__2wvrz {
  outline: none;
}
```

but it also globally includes Bulma's minireset without scopes, like:

```css
/*! minireset.css v0.0.4 | MIT License | github.com/jgthms/minireset.css */
html,
body,
p,
ol,
ul,
li,
dl,
dt,
dd,
blockquote,
figure,
fieldset,
legend,
textarea,
pre,
iframe,
hr,
h1,
h2,
h3,
h4,
h5,
h6 {
  margin: 0;
  padding: 0;
}
```

Any idea how to avoid importing Bulma's reset globally? (Note: bulma is already included on this site so this just duplicates existing rules but it also overrides some of the customizations I had made in the site that hosts the component).
