### ISSUE TITLE
can't run example build

### ISSUE THREAD

**Issue by FelipeLujan** [transitive-bullshit/create-react-library#235]
Hey.
First of all thanks for this awesome project.
I'm having an issue, after generating the static assets for the example project with `npm run build` I'm unable to run the generated files with:
```
npm install -g serve
serve -s build
```
This config that usually serves my react apps on Google App Engine, is unable to find the .js and .css files linked in build/index.html
```
runtime: nodejs10
env: standard
handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /
    static_dir: build
```

Thanks. Love this app

platform: windows 10 64bits
node v10.16.3
npm 6.11.3
