### ISSUE TITLE
Can't bundle css module

### ISSUE THREAD

**Issue by Innei** [transitive-bullshit/create-react-library#275]
Hi, guys. I wrote a component like this.

```
import * as React from 'react'

import styles from './index.module.css'

export const Player = React.forwardRef((props, ref) => {
//  ...

  return (
    <div className={styles['player-wrap']}>
      <div
        className={'inner-video' + ' ' + styles['blur-overlay']}
      >
       // ..
      </div>
    </div>
  )
})
```

and under same path `index.module.css`:

```css
.blur-overlay {
  position: relative;
}
.blur-overlay::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(255, 255, 255, 0.08);
  backdrop-filter: blur(20px);
}

```

But, It doesn't seem to be packed. css module hash is right, but where is css declare.

Hi, guys. I wrote a component like this.

```
import * as React from 'react'

import styles from './index.module.css'

export const Player = React.forwardRef((props, ref) => {
//  ...

  return (
    <div className={styles['player-wrap']}>
      <div
        className={'inner-video' + ' ' + styles['blur-overlay']}
      >
       // ..
      </div>
    </div>
  )
})
```

and under same path `index.module.css`:

```css
.blur-overlay {
  position: relative;
}
.blur-overlay::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(255, 255, 255, 0.08);
  backdrop-filter: blur(20px);
}

```

But, It doesn't seem to be packed. There is no CSS declaration.

<img width="1184" alt="Xnip2020-07-22_21-38-00" src="https://user-images.githubusercontent.com/41265413/88183136-a5942700-cc63-11ea-8e26-68fbe50804c3.png">
